### ISSUE TITLE
Fix product details in Stock

### ISSUE THREAD

**Issue by Timasostima** [Timasostima-RedondoDEV/EclipseBar#3]
![image](https://github.com/Timasostima-RedondoDEV/EclipseBar/assets/72166965/0a162d5d-ee0b-4124-be94-4b1769dc01b7)
![image](https://github.com/Timasostima-RedondoDEV/EclipseBar/assets/72166965/5fe0ed65-d47a-44b3-8369-a5379b0647dd)

**Comment by RedondoDev** [comment]
Done!
